/**
 * Report Service — generates investigation reports from analysis data
 */
const { getDb } = require('../db');

async function generateReport(analysisId, title) {
  const db = getDb();

  const analysis = db.prepare('SELECT * FROM analyses WHERE id=?').get(analysisId);
  const findings = db.prepare('SELECT * FROM findings WHERE analysis_id=? ORDER BY severity').all(analysisId);
  const iocs = db.prepare('SELECT * FROM iocs WHERE analysis_id=?').all(analysisId);
  const messages = db.prepare(
    "SELECT content FROM ai_messages WHERE analysis_id=? AND role='assistant' ORDER BY created_at"
  ).all(analysisId);

  let metadata = null;
  if (analysis.file_type === 'apk') {
    const apk = db.prepare('SELECT * FROM apk_metadata WHERE analysis_id=?').get(analysisId);
    if (apk) metadata = { ...apk, permissions: safeJSON(apk.permissions) };
  } else {
    const bin = db.prepare('SELECT * FROM binary_metadata WHERE analysis_id=?').get(analysisId);
    if (bin) metadata = { ...bin, imports: safeJSON(bin.imports), sections: safeJSON(bin.sections) };
  }

  const severityCounts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, INFO: 0 };
  for (const f of findings) severityCounts[f.severity] = (severityCounts[f.severity] || 0) + 1;

  const md = `# REForge Investigation Report
**File:** ${analysis.original_name}
**Type:** ${analysis.file_type?.toUpperCase()}
**Date:** ${new Date().toISOString().slice(0, 10)}
**SHA-256:** \`${analysis.sha256}\`
**MD5:** \`${analysis.md5}\`

---

## Executive Summary

${title || analysis.original_name} has been analyzed for malicious behavior. The automated scan identified **${findings.length} security findings** (${Object.entries(severityCounts).filter(([,v])=>v>0).map(([k,v])=>`${v} ${k}`).join(', ')}) and **${iocs.length} IOCs**.

${messages.length > 0 ? `\n**AI Analysis:** ${messages[messages.length-1].content.slice(0, 500)}...\n` : ''}

---

## File Metadata

| Field | Value |
|---|---|
| Filename | \`${analysis.original_name}\` |
| File Type | ${analysis.file_type} |
| Size | ${formatBytes(analysis.file_size)} |
| SHA-256 | \`${analysis.sha256}\` |
| MD5 | \`${analysis.md5}\` |
| Status | ${analysis.status} |
${metadata?.packageName ? `| Package | \`${metadata.packageName}\` |\n| Version | ${metadata.versionName} (${metadata.versionCode}) |\n| Min SDK | API ${metadata.minSdk} |\n| Target SDK | API ${metadata.targetSdk} |` : ''}
${metadata?.arch ? `| Architecture | ${metadata.arch} (${metadata.bits}-bit) |\n| Entry Point | \`${metadata.entry_point}\` |` : ''}

---

## Security Findings (${findings.length})

${findings.length === 0 ? '_No findings._' : findings.map(f => `
### [${f.severity}] ${f.title}
- **Category:** ${f.category}
- **Location:** \`${f.file_path}:${f.line_start || 'N/A'}\`
- **Description:** ${f.description || ''}
${f.evidence ? `\`\`\`\n${f.evidence}\n\`\`\`` : ''}
`).join('\n')}

---

## IOC List (${iocs.length})

${iocs.length === 0 ? '_No IOCs extracted._' : `
| Type | Value | File | Line |
|---|---|---|---|
${iocs.map(i => `| ${i.type} | \`${i.value.slice(0, 80)}\` | ${i.file_path || '-'} | ${i.line_number || '-'} |`).join('\n')}
`}

---

## AI Analysis Narrative

${messages.map(m => m.content).join('\n\n---\n\n') || '_No AI analysis performed yet. Use the AI Assistant to ask questions about this sample._'}

---

## Android Permissions

${metadata?.permissions ? safeJSON(metadata.permissions).map(p => `- \`${p}\``).join('\n') : '_N/A_'}

---

*Generated by REForge — AI Reverse Engineering Platform*
`;

  return { markdown: md };
}

function formatBytes(bytes) {
  if (!bytes) return 'Unknown';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function safeJSON(str) {
  try { return JSON.parse(str); } catch { return []; }
}

module.exports = { generateReport };
